import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

export default function Home() {
  return (
    <div className="home-container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="home-main">
        <h1 className="home-title">
          Welcome to <Link href="/">Goals!</Link>
        </h1>

        <p className="home-description">
          Paractice links of goals by <code className="home-code">Emumba</code>
        </p>

        <div className="home-grid">
          <Link href="/JsGoals" passHref>
            <article className="home-card">
              <h2>Javascript Goals &rarr;</h2>
              <p>
                All the Javascript Goals are{" "}
                <b>
                  <i>Here</i>
                </b>
              </p>
            </article>
          </Link>

          <Link href="/CssGoals" passHref>
            <article className="home-card">
              <h2>Css Goals &rarr;</h2>
              <p>
                {" "}
                All the Css Goals are{" "}
                <b>
                  <i>Here</i>
                </b>
              </p>
            </article>
          </Link>

          <Link href="/c" passHref>
            <article className="home-card">
              <h2>Examples &rarr;</h2>
              <p>Discover and deploy boilerplate example Next.js projects.</p>
            </article>
          </Link>

          <Link href="/d" passHref>
            <article className="home-card">
              <h2>Deploy &rarr;</h2>
              <p>
                Instantly deploy your Next.js site to a public URL with Vercel.
              </p>
            </article>
          </Link>
        </div>
      </main>

      <footer className="home-footer">
        <a target="_blank" rel="noopener noreferrer">
          Powered by
          <span className="home-logo">
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
